export const TOPICS = [
  "The psychology of procrastination and how to overcome it.",
  "The impact of vertical farming on urban sustainability.",
  "The rise of 'deepfake' technology and its societal implications.",
  "A historical look at the Silk Road and its role in cultural exchange.",
  "The science behind climate change and the evidence for global warming.",
  "An analysis of the gig economy and its effects on the modern workforce.",
  "The importance of biodiversity for ecosystem stability.",
  "A cultural study of minimalist lifestyles in Japan.",
  "The development of artificial intelligence in healthcare.",
  "Exploring the mysteries of dark matter and dark energy in the universe.",
  "The role of gut bacteria in human health and mood.",
  "How social media algorithms shape public opinion.",
  "The challenges and benefits of renewable energy sources like solar and wind power.",
  "A comparison of ancient Greek and Roman mythology.",
  "The psychological effects of living in a hyper-connected world.",
  "The history and cultural significance of coffee.",
  "Advancements in genetic engineering and CRISPR technology.",
  "The phenomenon of 'fast fashion' and its environmental cost.",
  "An exploration of the concept of 'flow state' in psychology and productivity.",
  "The conservation efforts to save endangered species.",
  "The architectural wonders of the ancient world.",
  "How sleep affects learning, memory, and physical health.",
  "The global issue of plastic pollution in our oceans.",
  "The evolution of video games as a form of art and storytelling.",
  "The principles of Stoic philosophy and their relevance today.",
  "The impact of space exploration on technological innovation.",
  "Understanding the process of photosynthesis and its importance for life on Earth.",
  "A look into the world of cybersecurity and the threat of digital espionage.",
  "The cultural and social impact of the printing press.",
  "The benefits of mindfulness and meditation for mental well-being.",
  "The ethics of AI in autonomous weapons systems.",
  "Biohacking: The science and risks of DIY biology.",
  "The role of 5G technology in the Internet of Things (IoT).",
  "Challenges in developing sustainable and efficient battery storage.",
  "How quantum computing could break modern encryption.",
  "The psychological impact of social media algorithms.",
  "Exploring the human microbiome and its effect on health.",
  "The race to commercialize fusion energy.",
  "The technology behind augmented reality and its applications.",
  "The Great Pacific Garbage Patch: causes and solutions.",
  "The effect of climate change on coral reef ecosystems.",
  "The debate over carbon taxing as a climate solution.",
  "The importance of protecting mangrove forests for coastal resilience.",
  "The environmental impact of the meat industry.",
  "Success stories in reintroducing endangered species to the wild.",
  "The science of permafrost thaw and its global consequences.",
  "The pros and cons of nuclear energy in a low-carbon future.",
  "The global water crisis and water management strategies.",
  "The concept of 'rewilding' urban spaces.",
  "The phenomenon of 'cancel culture' and free speech.",
  "The history and cultural significance of street art.",
  "The influence of Japanese anime and manga on global culture.",
  "The concept of universal basic income (UBI).",
  "How architecture reflects societal values.",
  "The preservation of indigenous languages and cultures.",
  "The changing definition of family in the 21st century.",
  "The history of the Olympic Games.",
  "The role of public libraries in the digital age.",
  "The placebo effect and the power of the mind in healing.",
  "The difference between introversion and shyness.",
  "Understanding cognitive dissonance and how it affects beliefs.",
  "The impact of sleep deprivation on cognitive function.",
  "The psychology behind conspiracy theories.",
  "The importance of emotional literacy in childhood development.",
  "The link between diet and mental health.",
  "The nature of impostor syndrome and how to combat it.",
  "The role of pets in improving human well-being.",
  "The art of effective time management for students.",
  "The basics of personal finance and budgeting.",
  "How to build healthy and lasting friendships.",
  "The importance of digital etiquette and online safety.",
  "The benefits of learning a new language.",
  "Developing effective public speaking skills.",
  "The value of volunteering and community service.",
  "Navigating conflicts with peers and family.",
  "The joy and challenges of learning to play a musical instrument.",
  "Tips for responsible and ethical travel.",
  "The science of how vaccines work.",
  "The history of cryptography from ancient ciphers to modern encryption.",
  "The impact of automation on the job market.",
  "The philosophy of existentialism and the search for meaning.",
  "The global supply chain and its vulnerabilities.",
  "The causes and effects of the 2008 financial crisis.",
  "The debate over net neutrality and the future of the internet.",
  "The cultural significance of food and cuisine around the world.",
  "The exploration of Mars and the search for extraterrestrial life.",
  "The principles of circular economy and sustainable design.",
  "The psychological phenomenon of cognitive biases.",
  "The history of the suffrage movement and the fight for women's right to vote.",
  "The impact of light pollution on wildlife and human health.",
  "The rise of streaming services and their effect on the film industry.",
  "The importance of critical thinking in the age of misinformation.",
  "The science of addiction and its effects on the brain.",
  "The concept of 'soft power' in international relations.",
  "The history and evolution of the English language.",
  "The role of bees and other pollinators in the ecosystem.",
  "The ethical considerations of animal testing in scientific research.",
  "The psychology of color and its use in marketing and design.",
  "The history of space stations, from Salyut to the ISS.",
  "The challenges of global food security in a growing population.",
  "The difference between equity and equality in social justice.",
  "The impact of invasive species on local ecosystems.",
  "The art of storytelling in different cultures and media.",
  "The science behind earthquakes and plate tectonics.",
  "The benefits and drawbacks of standardized testing in education.",
  "The history of animation, from hand-drawn to CGI.",
  "The social and economic impacts of urbanization.",
  "The role of empathy in communication and relationships.",
  "The science of lucid dreaming and its potential applications.",
  "The concept of 'growth mindset' versus 'fixed mindset'.",
  "The environmental effects of deforestation.",
  "The cultural impact of the Beatles.",
  "The challenges of providing clean drinking water globally.",
  "The science of memory: how we remember and why we forget.",
  "The history of money, from bartering to cryptocurrency.",
  "The importance of public transportation in sustainable cities.",
  "The psychology of persuasion and influence.",
  "The evolution of democratic systems of government.",
  "The impact of micro-transactions in the video game industry.",
  "The role of wetlands in filtering water and preventing floods.",
  "The history and philosophy of yoga.",
  "The science behind the Northern and Southern Lights.",
  "The ethical dilemmas of data collection by tech companies.",
  "The cultural significance of masks in different societies.",
  "The effects of noise pollution on human health.",
  "The principles of game theory and its application in real life.",
  "The history of the Cold War and the nuclear arms race.",
  "The challenges of waste management and recycling.",
  "The psychology of happiness and well-being.",
  "The evolution of fashion through the 20th century.",
  "The science of genetics and heredity.",
  "The role of non-governmental organizations (NGOs) in international aid.",
  "The history of cartography and map-making.",
  "The impact of tourism on local cultures and environments.",
  "The psychology of decision-making under pressure.",
  "The science behind volcanic eruptions.",
  "The history of public health and the fight against infectious diseases.",
  "The cultural importance of oral traditions and folklore.",
  "The future of work and the skills needed for it.",
  "The ethics of gene editing in humans with CRISPR-Cas9.",
  "The future of decentralized finance (DeFi) and its challenge to traditional banking.",
  "The James Webb Space Telescope's first images and their scientific significance.",
  "The concept of the 'metaverse': hype vs. reality.",
  "The global semiconductor shortage and its geopolitical implications.",
  "Analyzing the Trolley Problem and other ethical thought experiments.",
  "The rise of AI-generated art and its impact on creative professions.",
  "Understanding the basics of quantum computing and its potential.",
  "The historical accuracy of popular films and TV series.",
  "The cultural impact of K-Pop and the Hallyu wave.",
  "Debunking common myths about nutrition and diet.",
  "The psychology of 'doomscrolling' and how to manage information overload.",
  "The history and revival of the Stoic philosophy for modern life.",
  "The challenges of colonizing Mars and creating a self-sustaining habitat.",
  "The role of dark patterns in user interface design.",
  "Exploring the lost city of Pompeii and what it tells us about Roman life.",
  "The science behind nuclear fusion and its promise of clean energy.",
  "The debate over data privacy in the age of big tech.",
  "The socio-economic impact of the 'Great Resignation'.",
  "How language shapes our perception of reality (the Sapir-Whorf hypothesis).",
  "The environmental impact of cryptocurrency mining.",
  "The history of the Enigma machine and its role in World War II.",
  "The potential for lab-grown meat to solve food crises.",
  "The importance of preserving ancient languages.",
  "The concept of a circular economy versus a linear economy.",
  "The influence of classical music on modern movie soundtracks.",
  "The phenomenon of 'imposter syndrome' in high achievers.",
  "The future of remote work and its effect on urban centers.",
  "The science of sleep and the importance of circadian rhythms.",
  "The philosophical concept of 'Ship of Theseus' in identity.",
  "How misinformation spreads online and how to identify it.",
  "The geopolitics of rare earth minerals.",
  "The benefits of developing emotional intelligence (EQ).",
  "The history of urban planning and the design of modern cities.",
  "The psychological effects of architecture and interior design.",
  "The rise of the creator economy and monetization platforms.",
  "The science of extremophiles: life in the harshest environments.",
  "The cultural significance of the Silk Road in ancient times.",
  "The debate over nuclear energy's role in combating climate change.",
  "The challenges and ethics of deep-sea mining.",
  "The impact of the gut-brain axis on mental health.",
  "The history and rules of chess and its cognitive benefits.",
  "The future of personalized medicine based on genetic profiles.",
  "The role of satire in political commentary.",
  "The science behind optical illusions.",
  "The restoration of Notre Dame Cathedral after the 2019 fire.",
  "The concept of 'digital nomadism' and its lifestyle implications.",
  "The exploration of hydrothermal vents and deep-sea ecosystems.",
  "The history of the Rosetta Stone and deciphering hieroglyphs.",
  "The use of blockchain technology for supply chain transparency.",
  "The impact of agricultural pesticides on the environment.",
  "The psychology of conformity and obedience.",
  "The history and art of photography.",
  "The science of tidal energy as a renewable resource.",
  "The concept of cultural heritage and its preservation.",
  "The effects of caffeine on the human body.",
  "The history of the internet, from ARPANET to the World Wide Web.",
  "The role of public art in urban spaces.",
  "The psychology of motivation and setting goals.",
  "The science behind the changing of the seasons.",
  "The challenges of refugee crises and international law.",
  "The cultural significance of tattoos throughout history.",
  "The impact of e-commerce on traditional retail.",
  "The psychology of first impressions.",
  "The science of soil health and its importance for agriculture.",
  "The history of the Renaissance and its impact on art and science.",
  "The ethics of journalism in the digital age.",
  "The role of comedy in social commentary.",
  "The challenges of preserving digital information for the future.",
  "The psychology of fear and anxiety.",
  "The science of sound and acoustics.",
  "The history of the Industrial Revolution and its societal changes.",
  "The importance of clean oceans for the planet's health.",
  "The cultural evolution of dance forms.",
  "The psychology of habit formation.",
  "The science behind weather forecasting.",
  "The history and principles of democracy.",
  "The impact of influencer culture on social media.",
  "The challenges of space debris and orbital pollution.",
  "The psychology of creativity and innovation.",
  "The history of ancient civilizations in Mesopotamia.",
  "The role of forests as carbon sinks.",
  "The cultural importance of festivals and celebrations.",
  "The science of taste and smell.",
  "The psychology of group dynamics and teamwork.",
  "The history of flight, from the Wright brothers to supersonic jets.",
  "The impact of fast food on global health.",
  "The ethics of artificial intelligence in decision-making.",
  "The cultural significance of fairy tales.",
  "The science of composting and its environmental benefits.",
  "The psychology of memory and eyewitness testimony.",
  "The history of the Roman Empire.",
  "The challenges of sustainable fashion.",
  "The role of music in film and storytelling.",
  "The science of bioluminescence in nature.",
  "The psychology of learning and different learning styles.",
  "The history of medicine and major breakthroughs.",
  "The impact of online gaming communities.",
  "The importance of urban green spaces for well-being.",
  "The psychology of risk perception.",
  "The science of snowflakes and crystal formation.",
  "The history of exploration and discovery.",
  "The ethics of zoos and wildlife conservation.",
  "The cultural impact of Shakespeare's plays.",
  "The psychology of altruism and helping behavior.",
  "The science of allergies and the immune system.",
  "The history of the Civil Rights Movement in the United States.",
  "The challenges of managing electronic waste (e-waste).",
  "The role of mythology in shaping cultural identity.",
  "The psychology of nostalgia.",
  "The science behind rainbows and light refraction.",
  "The history of architecture and its various styles.",
  "The impact of the sharing economy (e.g., Airbnb, Uber).",
  "The ethics of intellectual property in the digital age.",
  "The cultural significance of tea in different societies.",
  "The science of bird migration.",
  "The psychology of sleep and dreams.",
  "The history of the scientific method.",
  "The global issue of food waste.",
  "The cultural impact of hip-hop music.",
  "The psychology of personality theories.",
  "The science of geology and the rock cycle.",
  "The history of telecommunication, from the telegraph to the smartphone.",
  "The role of satire in political discourse.",
  "The challenges of desertification and land degradation.",
  "The psychology of body language and nonverbal communication.",
  "The history of the Vikings.",
  "The science of forensics and crime scene investigation.",
  "The cultural importance of handcrafted goods and artisanship.",
  "The psychology of advertising and consumer behavior.",
  "The science of human evolution.",
  "The history of the Silk Road and its cultural impact.",
  "The challenges of light pollution for astronomy.",
  "The role of dance in cultural expression.",
  "The psychology of stress and coping mechanisms.",
  "The science of water's unique properties.",
  "The history of the Crusades.",
  "The impact of social movements on societal change.",
  "The ethics of big data and privacy.",
  "The cultural significance of clothing and fashion.",
  "The science of fire and combustion.",
  "The psychology of leadership and its different styles.",
  "The history of ancient Greece and its philosophical legacy.",
  "The global problem of overfishing.",
  "The cultural role of poetry throughout the ages.",
  "The psychology of motivation in sports.",
  "The science of climate patterns like El Niño and La Niña.",
  "The history of the Mongol Empire.",
  "The impact of citizen science on research.",
  "The ethics of genetic screening.",
  "The cultural history of the automobile.",
  "The science of spider silk and its potential applications.",
  "The psychology of prejudice and discrimination.",
  "The history of the Aztec civilization.",
  "The challenges of air pollution in major cities.",
  "The cultural significance of gardens in different cultures.",
  "The science of static electricity.",
  "The psychology of attachment in relationships.",
  "The history of espionage and intelligence agencies.",
  "The impact of technology on modern education.",
  "The ethics of using performance-enhancing drugs in sports.",
  "The cultural evolution of comic books and graphic novels.",
  "The science of animal camouflage.",
  "The psychology of behavioral economics.",
  "The history of the Byzantine Empire.",
  "The environmental benefits of reforestation.",
  "The cultural role of museums in preserving history.",
  "The science of magnetism.",
  "The psychology of cognitive development in children.",
  "The history of the Ottoman Empire.",
  "The challenges of achieving gender equality worldwide.",
  "The ethics of space exploration and colonization.",
  "The cultural importance of martial arts.",
  "The science of sound waves and music.",
  "The psychology of moral development.",
  "The history of the Persian Empire.",
  "The impact of social media on mental health.",
  "The benefits of bilingualism on the brain.",
  "The cultural history of board games.",
  "The science of plate tectonics and continental drift.",
  "The psychology of social influence.",
  "The history of the Maya civilization.",
  "The challenges of transitioning to electric vehicles.",
  "The cultural significance of mythology in modern storytelling.",
  "The science of sleep cycles (REM and NREM).",
  "The psychology of memory consolidation.",
  "The history of the Inca Empire.",
  "The impact of agricultural runoff on water quality.",
  "The ethics of using artificial intelligence in art creation.",
  "The cultural history of theater.",
  "The science of the human eye and vision.",
  "The psychology of intrinsic vs. extrinsic motivation.",
  "The history of ancient China's dynasties.",
  "The challenge of dealing with antibiotic resistance.",
  "The cultural significance of body adornment and jewelry.",
  "The science of hibernation in animals.",
  "The psychology of resilience and overcoming adversity.",
  "The history of the Age of Enlightenment.",
  "The impact of noise pollution on marine life.",
  "The ethics of 'voluntourism' (volunteer tourism).",
  "The cultural history of radio broadcasting.",
  "The science of the greenhouse effect.",
  "The psychology of self-esteem.",
  "The history of the French Revolution.",
  "The challenges of cryptocurrency regulation.",
  "The cultural importance of storytelling in indigenous cultures.",
  "The science of the human brain's plasticity.",
  "The psychology of persuasion in political campaigns.",
  "The history of the Russian Revolution.",
  "The impact of urban sprawl on the environment.",
  "The ethics of consuming media from controversial artists.",
  "The cultural history of animated films.",
  "The science of photosynthesis in plants.",
  "The psychology of stereotypes and their impact.",
  "The history of the Age of Discovery.",
  "The challenges of biodiversity loss.",
  "The cultural importance of national parks and protected areas.",
  "The science of the human sense of touch.",
  "The psychology of bystander effect.",
  "The history of the Protestant Reformation.",
  "The impact of food additives on health.",
  "The ethics of using animals in entertainment.",
  "The cultural history of the novel.",
  "The science of solar flares and their effect on Earth.",
  "The psychology of emotional regulation.",
  "The history of the American Revolution.",
  "The challenges of global vaccine distribution.",
  "The cultural importance of culinary traditions.",
  "The science of the tides.",
  "The psychology of goal-setting and achievement.",
  "The history of the Scientific Revolution.",
  "The impact of deforestation on indigenous communities.",
  "The ethics of fast fashion and labor practices.",
  "The cultural history of photography.",
  "The science of the Earth's magnetic field.",
  "The psychology of cognitive biases in decision making.",
  "The history of World War I.",
  "The challenges of water scarcity and conservation.",
  "The cultural importance of public holidays.",
  "The science of the human digestive system.",
  "The psychology of social comparison on social media.",
  "The history of World War II.",
  "The impact of single-use plastics on the environment.",
  "The ethics of reality television.",
  "The cultural history of jazz music.",
  "The science of the carbon cycle.",
  "The psychology of memory biases.",
  "The history of the Cold War.",
  "The challenges of sustainable agriculture.",
  "The cultural importance of architecture in city identity.",
  "The science of the human nervous system.",
  "The psychology of obedience to authority.",
  "The history of the Vietnam War.",
  "The impact of the gig economy on labor markets.",
  "The ethics of using AI in hiring processes.",
  "The cultural history of rock and roll.",
  "The science of the water cycle.",
  "The psychology of the fundamental attribution error.",
  "The history of the Korean War.",
  "The challenges of managing invasive plant species.",
  "The cultural importance of rites of passage.",
  "The science of the human circulatory system.",
  "The psychology of attribution theory.",
  "The history of the fall of the Soviet Union.",
  "The impact of deep-sea mining on ocean ecosystems.",
  "The ethics of using user data for targeted advertising.",
  "The cultural history of folk music.",
  "The science of the human respiratory system.",
  "The psychology of social identity theory.",
  "The history of apartheid in South Africa.",
  "The challenges of soil erosion and degradation.",
  "The cultural importance of traditional medicine.",
  "The science of the human skeletal system.",
  "The psychology of cognitive dissonance.",
  "The history of the Israeli-Palestinian conflict.",
  "The impact of climate change on agriculture.",
  "The ethics of 'cancel culture' and public shaming.",
  "The cultural history of classical music.",
  "The science of the human muscular system.",
  "The psychology of groupthink.",
  "The history of the Rwandan genocide.",
  "The challenges of plastic recycling.",
  "The cultural importance of local dialects and languages.",
  "The science of the human endocrine system.",
  "The psychology of self-fulfilling prophecies.",
  "The history of the women's suffrage movement.",
  "The impact of artificial light at night on ecosystems.",
  "The ethics of using AI in the justice system.",
  "The cultural history of opera.",
  "The science of the human immune system.",
  "The psychology of confirmation bias.",
  "The history of the Industrial Revolution in Britain.",
  "The challenges of renewable energy storage.",
  "The cultural importance of national cuisines.",
  "The science of the human reproductive system.",
  "The psychology of the availability heuristic.",
  "The history of the Tiananmen Square protests.",
  "The impact of tourism on fragile ecosystems.",
  "The ethics of gene editing in humans.",
  "The cultural history of ballet.",
  "The science of the human integumentary system (skin).",
  "The psychology of the representativeness heuristic.",
  "The history of the development of the European Union.",
  "The challenges of protecting endangered languages.",
  "The cultural importance of pilgrimage sites.",
  "The science of cellular respiration.",
  "The psychology of the anchoring effect.",
  "The history of the unification of Germany.",
  "The impact of commercial fishing on marine biodiversity.",
  "The ethics of using facial recognition technology.",
  "The cultural history of country music.",
  "The science of DNA and genetic inheritance.",
  "The psychology of framing effects in communication.",
  "The history of the Scramble for Africa.",
  "The challenges of sustainable urban planning.",
  "The cultural importance of traditional clothing.",
  "The science of osmosis and diffusion.",
  "The psychology of loss aversion.",
  "The history of the Spanish conquest of the Americas.",
  "The impact of hydroelectric dams on rivers.",
  "The ethics of geoengineering to combat climate change.",
  "The cultural history of electronic dance music (EDM).",
  "The science of chemical reactions.",
  "The psychology of the sunk cost fallacy.",
  "The history of the Trans-Atlantic slave trade.",
  "The challenges of managing nuclear waste.",
  "The cultural importance of cemeteries and burial customs.",
  "The science of acids and bases.",
  "The psychology of herd mentality.",
  "The history of the Meiji Restoration in Japan.",
  "The impact of the fashion industry on water resources.",
  "The ethics of creating 'designer babies'.",
  "The cultural history of musical theater.",
  "The science of the states of matter.",
  "The psychology of the Dunning-Kruger effect.",
  "The history of the Russian Empire.",
  "The challenges of preserving historical artifacts.",
  "The cultural importance of public squares and plazas.",
  "The science of energy conservation.",
  "The psychology of the halo effect.",
  "The history of the British Empire.",
  "The impact of monoculture farming on biodiversity.",
  "The ethics of using social credit systems.",
  "The cultural history of punk rock.",
  "The science of thermodynamics.",
  "The psychology of the just-world hypothesis.",
  "The history of the Qing Dynasty in China.",
  "The challenges of balancing economic development and environmental protection.",
  "The cultural importance of traditional festivals.",
  "The science of simple machines.",
  "The psychology of optimism and pessimism.",
  "The history of the Mughal Empire in India.",
  "The impact of oil spills on marine environments.",
  "The ethics of mandatory vaccinations.",
  "The cultural history of blues music.",
  "The science of Newton's laws of motion.",
  "The psychology of the spotlight effect.",
  "The history of the Abolitionist movement.",
  "The challenges of global poverty and inequality.",
  "The cultural importance of street food.",
  "The science of gravity and its effects.",
  "The psychology of cognitive load in learning.",
  "The history of the temperance movement.",
  "The impact of agricultural subsidies on the global market.",
  "The ethics of using AI to generate news articles.",
  "The cultural history of reggae music.",
  "The science of friction and its applications.",
  "The psychology of chunking in memory.",
  "The history of the labor movement and workers' rights.",
  "The challenges of international cooperation on climate change.",
  "The cultural importance of traditional crafts.",
  "The science of momentum and impulse.",
  "The psychology of spaced repetition in learning.",
  "The history of the environmental movement.",
  "The impact of microfinance on developing economies.",
  "The ethics of animal captivity for entertainment.",
  "The cultural history of funk music.",
  "The science of work, energy, and power.",
  "The psychology of retrieval practice in learning.",
  "The history of the peace movement.",
  "The challenges of food deserts in urban areas.",
  "The cultural importance of public parks.",
  "The science of buoyancy and density.",
  "The psychology of interleaving in study habits.",
  "The history of the disability rights movement.",
  "The impact of remittances on home countries.",
  "The ethics of using autonomous drones in warfare.",
  "The cultural history of soul music.",
  "The science of pressure in fluids and gases.",
  "The psychology of dual coding theory in education.",
  "The history of the LGBTQ+ rights movement.",
  "The challenges of achieving universal literacy.",
  "The cultural importance of farmers' markets.",
  "The science of simple harmonic motion.",
  "The psychology of self-explanation while learning.",
  "The history of the anti-globalization movement.",
  "The impact of brain drain on developing nations.",
  "The ethics of using deepfake technology.",
  "The cultural history of gospel music.",
  "The science of waves (transverse and longitudinal).",
  "The psychology of the testing effect.",
  "The history of the feminist movement.",
  "The challenges of global health security.",
  "The cultural importance of community gardens.",
  "The science of the Doppler effect.",
  "The psychology of mindset (growth vs. fixed).",
  "The history of the counter-culture movement of the 1960s.",
  "The impact of Fair Trade practices on producers.",
  "The ethics of human cloning.",
  "The cultural history of Latin music.",
  "The science of light reflection and refraction.",
  "The psychology of metacognition (thinking about thinking).",
  "The history of the punk rock movement.",
  "The challenges of digital literacy in an aging population.",
  "The cultural importance of public libraries.",
  "The science of lenses and optical instruments.",
  "The psychology of motivation and self-determination theory.",
  "The history of the civil rights movement in Northern Ireland.",
  "The impact of gentrification on urban neighborhoods.",
  "The ethics of using AI for emotional analysis.",
  "The cultural history of Bollywood films.",
  "The science of color and light spectrum.",
  "The psychology of emotional intelligence.",
  "The history of the quiet revolution in Quebec.",
  "The challenges of sustainable tourism.",
  "The cultural importance of traditional music.",
  "The science of electricity and circuits.",
  "The psychology of social cognition.",
  "The history of the Velvet Revolution in Czechoslovakia.",
  "The impact of globalization on cultural identity.",
  "The ethics of using AI in creative industries.",
  "The cultural history of Japanese cinema.",
  "The science of electric charge and fields.",
  "The psychology of attitude formation and change.",
  "The history of the Solidarity movement in Poland.",
  "The challenges of preserving intangible cultural heritage.",
  "The cultural importance of religious architecture.",
  "The science of voltage, current, and resistance.",
  "The psychology of persuasion and social compliance.",
  "The history of the fall of the Berlin Wall.",
  "The impact of cultural exchange programs.",
  "The ethics of using algorithms in criminal sentencing.",
  "The cultural history of French New Wave cinema.",
  "The science of magnets and magnetic fields.",
  "The psychology of interpersonal attraction.",
  "The history of the Arab Spring.",
  "The challenges of multiculturalism in society.",
  "The cultural importance of oral history.",
  "The science of electromagnetism.",
  "The psychology of close relationships.",
  "The history of the Occupy Wall Street movement.",
  "The impact of international trade on domestic jobs.",
  "The ethics of using AI to replace human jobs.",
  "The cultural history of Italian neorealism cinema.",
  "The science of electromagnetic induction.",
  "The psychology of prosocial behavior.",
  "The history of the Black Lives Matter movement.",
  "The challenges of political polarization.",
  "The cultural importance of public monuments and memorials.",
  "The science of electromagnetic waves.",
  "The psychology of aggression and conflict.",
  "The history of the #MeToo movement.",
  "The impact of foreign aid on economic development.",
  "The ethics of using AI in personalized education.",
  "The cultural history of German expressionist cinema.",
  "The science of special relativity.",
  "The psychology of prejudice and stereotyping.",
  "The history of the Hong Kong protests.",
  "The challenges of misinformation and 'fake news'.",
  "The cultural importance of historical reenactments.",
  "The science of general relativity.",
  "The psychology of intergroup relations.",
  "The history of the Zapatista uprising in Mexico.",
  "The impact of multinational corporations on developing countries.",
  "The ethics of using AI in mental health diagnosis.",
  "The cultural history of Soviet montage cinema.",
  "The science of quantum mechanics.",
  "The psychology of conflict resolution.",
  "The history of the American Indian Movement.",
  "The challenges of global governance.",
  "The cultural importance of botanical gardens.",
  "The science of the atom and its structure.",
  "The psychology of negotiation and bargaining.",
  "The history of the Chicano Movement.",
  "The impact of remittances on family economies.",
  "The ethics of using AI in autonomous vehicles.",
  "The cultural history of film noir.",
  "The science of the periodic table of elements.",
  "The psychology of social perception.",
  "The history of the Asian American movement.",
  "The challenges of intellectual property rights in a globalized world.",
  "The cultural importance of world heritage sites.",
  "The science of chemical bonding.",
  "The psychology of self-perception.",
  "The history of the Stonewall Uprising.",
  "The impact of microplastics on human health.",
  "The ethics of using AI in financial trading.",
  "The cultural history of the Western genre in film.",
  "The science of molecular geometry.",
  "The psychology of nonverbal communication.",
  "The history of the Young Lords.",
  "The challenges of global migration patterns.",
  "The cultural importance of natural history museums.",
  "The science of intermolecular forces.",
  "The psychology of impression management.",
  "The history of the anti-apartheid movement.",
  "The impact of the sharing economy on urban housing.",
  "The ethics of using AI to monitor employees.",
  "The cultural history of science fiction films.",
  "The science of stoichiometry.",
  "The psychology of self-presentation.",
  "The history of the Green Revolution in agriculture.",
  "The challenges of urban heat islands.",
  "The cultural importance of science museums.",
  "The science of gas laws.",
  "The psychology of social roles and norms.",
  "The history of the Bretton Woods system.",
  "The impact of the Panama Papers on global finance.",
  "The ethics of using AI in military intelligence.",
  "The cultural history of horror films.",
  "The science of solutions and concentration.",
  "The psychology of conformity.",
  "The history of the Non-Aligned Movement.",
  "The challenges of ocean acidification.",
  "The cultural importance of art galleries.",
  "The science of reaction rates.",
  "The psychology of obedience.",
  "The history of the OPEC oil crisis.",
  "The impact of the Belt and Road Initiative.",
  "The ethics of using AI in predicting criminal behavior.",
  "The cultural history of fantasy films.",
  "The science of chemical equilibrium.",
  "The psychology of social facilitation.",
  "The history of decolonization in Africa and Asia.",
  "The challenges of preserving coral reefs.",
  "The cultural importance of performing arts centers.",
  "The science of acid-base chemistry.",
  "The psychology of social loafing.",
  "The history of the development of international law.",
  "The impact of the Suez Canal on global trade.",
  "The ethics of using AI in healthcare decisions.",
  "The cultural history of documentary films.",
  "The science of redox reactions.",
  "The psychology of deindividuation.",
  "The history of the creation of the United Nations.",
  "The challenges of protecting rainforests.",
  "The cultural importance of zoos and aquariums.",
  "The science of electrochemistry.",
  "The psychology of group polarization.",
  "The history of the Marshall Plan.",
  "The impact of the rise of emerging economies.",
  "The ethics of using AI in personalized marketing.",
  "The cultural history of experimental films.",
  "The science of nuclear chemistry.",
  "The psychology of minority influence.",
  "The history of the Universal Declaration of Human Rights.",
  "The challenges of managing global pandemics.",
  "The cultural importance of national archives.",
  "The science of organic chemistry.",
  "The psychology of leadership.",
  "The history of the Nuremberg trials.",
  "The impact of automation on manufacturing.",
  "The ethics of using AI to create art.",
  "The cultural history of silent films.",
  "The science of biochemistry.",
  "The psychology of transactional and transformational leadership.",
  "The history of the space race.",
  "The challenges of cybersecurity in a connected world.",
  "The cultural importance of food markets.",
  "The science of polymers.",
  "The psychology of power and influence.",
  "The history of the development of the internet.",
  "The impact of digital currencies on the economy.",
  "The ethics of using AI in education.",
  "The cultural history of propaganda films.",
  "The science of materials science.",
  "The psychology of social networks.",
  "The history of the Human Genome Project.",
  "The challenges of an aging global population.",
  "The cultural importance of musical traditions.",
  "The science of nanotechnology.",
  "The psychology of online communities.",
  "The history of the discovery of penicillin.",
  "The impact of climate change on migration.",
  "The ethics of using AI in journalism.",
  "The cultural history of independent cinema.",
  "The science of environmental chemistry.",
  "The psychology of virtual identity.",
  "The history of the development of computers.",
  "The challenges of urban transportation systems.",
  "The cultural importance of traditional dance.",
  "The science of atmospheric science.",
  "The psychology of cyberbullying.",
  "The history of the discovery of DNA structure.",
  "The impact of remote work on city economies.",
  "The ethics of using AI in warfare.",
  "The cultural history of avant-garde art.",
  "The science of oceanography.",
  "The psychology of online relationships.",
  "The history of the theory of evolution.",
  "The challenges of income inequality.",
  "The cultural importance of culinary arts.",
  "The science of meteorology.",
  "The psychology of social media addiction.",
  "The history of the theory of relativity.",
  "The impact of educational technology on learning.",
  "The ethics of using AI to write code.",
  "The cultural history of surrealism.",
  "The science of climatology.",
  "The psychology of decision fatigue.",
  "The history of the development of quantum mechanics.",
  "The challenges of food sustainability.",
  "The cultural importance of textile arts.",
  "The science of hydrology.",
  "The psychology of the fear of missing out (FOMO).",
  "The history of the Big Bang theory.",
  "The impact of the attention economy.",
  "The ethics of using AI in scientific research.",
  "The cultural history of cubism.",
  "The science of geology.",
  "The psychology of information overload.",
  "The history of the discovery of electricity.",
  "The challenges of mental health awareness.",
  "The cultural importance of calligraphy.",
  "The science of paleontology.",
  "The psychology of multitasking.",
  "The history of the development of the telephone.",
  "The impact of celebrity culture on society.",
  "The ethics of using AI in therapy.",
  "The cultural history of impressionism.",
  "The science of archaeology.",
  "The psychology of digital minimalism.",
  "The history of the development of the automobile.",
  "The challenges of preserving cultural identity in a globalized world.",
  "The cultural importance of pottery and ceramics.",
  "The science of anthropology.",
  "The psychology of gamification.",
  "The history of the development of the airplane.",
  "The impact of fast fashion on consumer behavior.",
  "The ethics of using AI to create music.",
  "The cultural history of post-impressionism.",
  "The science of sociology.",
  "The psychology of choice paralysis.",
  "The history of the development of radio.",
  "The challenges of sustainable living.",
  "The cultural importance of woodworking and carpentry.",
  "The science of ecology.",
  "The psychology of the paradox of choice.",
  "The history of the development of television.",
  "The impact of consumerism on the environment.",
  "The ethics of using AI to simulate deceased individuals.",
  "The cultural history of abstract expressionism.",
  "The science of botany.",
  "The psychology of branding and consumer loyalty.",
  "The history of the development of nuclear power.",
  "The challenges of ethical consumerism.",
  "The cultural importance of glassblowing.",
  "The science of zoology.",
  "The psychology of marketing to children.",
  "The history of the development of plastics.",
  "The impact of the wellness industry on health.",
  "The ethics of using AI to influence elections.",
  "The cultural history of pop art.",
  "The science of entomology.",
  "The psychology of nostalgia in advertising.",
  "The history of the development of antibiotics.",
  "The challenges of urban gardening.",
  "The cultural importance of metalworking and blacksmithing.",
  "The science of ornithology.",
  "The psychology of greenwashing in marketing.",
  "The history of the development of vaccines.",
  "The impact of minimalist lifestyles on well-being.",
  "The ethics of using AI in companionship roles.",
  "The cultural history of minimalism in art.",
  "The science of marine biology.",
  "The psychology of viral content and internet memes.",
  "The history of the development of anesthesia.",
  "The challenges of reducing personal carbon footprints.",
  "The cultural importance of storytelling in business.",
  "The science of primatology.",
  "The psychology of online privacy.",
  "The history of the development of antiseptics.",
  "The impact of community-supported agriculture (CSA).",
  "The ethics of using AI to automate creative jobs.",
  "The cultural history of conceptual art.",
  "The science of genetics.",
  "The psychology of digital identity and self.",
  "The history of the development of the printing press.",
  "The challenges of zero-waste living.",
  "The cultural importance of folk remedies and traditional healing.",
  "The science of microbiology.",
  "The psychology of online communities and belonging.",
  "The history of the development of the steam engine.",
  "The impact of the slow food movement.",
  "The ethics of AI in autonomous decision-making.",
  "The cultural history of performance art.",
  "The science of virology.",
  "The psychology of online activism and 'slacktivism'.",
  "The history of the development of the telegraph.",
  "The challenges of affordable housing in cities.",
  "The cultural importance of ancient ruins and archaeological sites.",
  "The science of mycology (study of fungi).",
  "The psychology of online learning effectiveness.",
  "The history of the development of the railroad.",
  "The impact of urban renewal projects on communities.",
  "The ethics of AI consciousness and rights.",
  "The cultural history of street art and graffiti.",
  "The science of immunology.",
  "The psychology of remote work and productivity.",
  "The history of the development of the skyscraper.",
  "The challenges of food security and distribution.",
  "The cultural importance of pilgrimage trails.",
  "The science of pharmacology.",
  "The psychology of technology's impact on child development.",
  "The history of the development of the suspension bridge.",
  "The impact of universal basic income experiments.",
  "The ethics of algorithmic bias in society.",
  "The cultural history of landscape painting.",
  "The science of toxicology.",
  "The psychology of the digital divide.",
  "The history of the development of the canal system.",
  "The challenges of preserving biodiversity hotspots.",
  "The cultural importance of traditional agricultural practices.",
  "The science of epidemiology.",
  "The psychology of technology and its effect on sleep.",
  "The history of the development of the postal service.",
  "The impact of online reviews on consumer choice.",
  "The ethics of using AI for predictive policing.",
  "The cultural history of portrait painting.",
  "The science of pathology.",
  "The psychology of human-computer interaction.",
  "The history of the development of public education.",
  "The challenges of wildlife trafficking.",
  "The cultural importance of sacred natural sites.",
  "The science of physiology.",
  "The psychology of technology and attention spans.",
  "The history of the development of universities.",
  "The impact of the tiny house movement.",
  "The ethics of using AI in artistic creation.",
  "The cultural history of still life painting.",
  "The science of anatomy.",
  "The psychology of social comparison and envy online.",
  "The history of the development of public libraries.",
  "The challenges of managing electronic waste.",
  "The cultural importance of traditional weaving and textiles.",
  "The science of neuroscience.",
  "The psychology of online dating and relationships.",
  "The history of the development of museums.",
  "The impact of co-working spaces on work culture.",
  "The ethics of AI in personal assistants.",
  "The cultural history of Renaissance art.",
  "The science of endocrinology.",
  "The psychology of the 'filter bubble' effect.",
  "The history of the development of the newspaper.",
  "The challenges of food labeling and transparency.",
  "The cultural importance of traditional puppetry.",
  "The science of gastroenterology.",
  "The psychology of echo chambers online.",
  "The history of the development of the book.",
  "The impact of the local food movement.",
  "The ethics of AI in medical diagnosis.",
  "The cultural history of Baroque art.",
  "The science of cardiology.",
  "The psychology of misinformation spread.",
  "The history of the development of writing.",
  "The challenges of antibiotic overuse in agriculture.",
  "The cultural importance of traditional theater forms.",
  "The science of dermatology.",
  "The psychology of online shaming and 'doxing'.",
  "The history of the development of agriculture.",
  "The impact of ride-sharing services on public transport.",
  "The ethics of AI in legal research.",
  "The cultural history of Rococo art.",
  "The science of hematology.",
  "The psychology of parasocial relationships with online figures.",
  "The history of the development of cities.",
  "The challenges of protecting intellectual property online.",
  "The cultural importance of traditional music instruments.",
  "The science of nephrology.",
  "The psychology of influencer marketing.",
  "The history of the development of law.",
  "The impact of streaming services on media consumption.",
  "The ethics of AI in automated journalism.",
  "The cultural history of Neoclassical art.",
  "The science of oncology.",
  "The psychology of 'doomscrolling' and its effects.",
  "The history of the development of government.",
  "The challenges of digital preservation.",
  "The cultural importance of traditional storytelling.",
  "The science of ophthalmology.",
  "The psychology of 'virtue signaling' online.",
  "The history of the development of religion.",
  "The impact of the maker movement on innovation.",
  "The ethics of using AI in creating personalized advertisements.",
  "The cultural history of Romanticism in art.",
  "The science of pulmonology.",
  "The psychology of online trolling and cyber-aggression."
];
